name: CI

defaults:
  run:
    working-directory: build

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

# Explicitly grant permissions to create a release
permissions:
  contents: write

jobs:
  create-release: # Fixed typo: was "create-releae"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: build

      - name: Branch Name
        id: branch_name
        run: |
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Package
        run: |
          mkdir strichliste
          
          # Dynamically downloading the backend and frontend artifacts based on the pushed tag
          wget https://github.com/strichliste/strichliste-backend/releases/download/v2.1.0/strichliste-backend-v2.1.0.tar.gz -O strichliste-backend.tar.gz
          wget https://github.com/strichliste/strichliste-web-frontend/releases/download/v2.1.0/strichliste-web-frontend.tar.gz -O strichliste-web-frontend.tar.gz
          
          tar xfz strichliste-backend.tar.gz -C strichliste
          tar xfz strichliste-web-frontend.tar.gz --strip 1 -C strichliste/public/
          
          cd strichliste/
          # Naming the tarball correctly right from the start and placing it in the build directory
          tar cfz ../strichliste-${{ steps.branch_name.outputs.SOURCE_TAG }}.tar.gz .env *

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: Release ${{ steps.branch_name.outputs.SOURCE_TAG }}
          tag_name: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          files: build/strichliste-${{ steps.branch_name.outputs.SOURCE_TAG }}.tar.gz
